- hosts: client
  become: yes
  tasks:
    - name: Apache Install
      include_tasks: apache.yml

    - name: PHP Install
      include_tasks: php.yml

    - name: Mysql Install
      include_tasks: mysql.yml

    - name: Download and Install Modx
      include_tasks: download_and_extracting_modx.yml
